In [29]:
%run Nonlinear_Dynamics
import numpy as np
import pylab as pl
def solve_sdof(max_time=10.0, A = 1.2, w = 2, x0 = 0, v0 = 0, plotnow = 1):

    
    def sdof_deriv(x1_x2, t, A = 1.2, w = 2):
        """Compute the time-derivative of a SDOF system."""
        x1, x2 = x1_x2
        return [x2, -x2 - x1 - x1**3 + A*np.cos(w*t)]

    x0i=((x0, v0))
    # Solve for the trajectories
    t = sp.linspace(0, max_time, int(250*max_time))
    x_t = sp.integrate.odeint(sdof_deriv, x0i, t)
    
    x, v = x_t.T
    f = A*np.cos(w*t)
    
    if plotnow == 1:
        #fig = plt.figure()
        #ax = fig.add_axes([0, 0, 1, 1], projection='3d')
        plt.plot(t,x,t,f,'--')
        pl.legend(['x','Forcing Function'])
        plt.xlabel('Time (s)')
        plt.ylabel('x')
        plt.title('Integrated Response of the Duffing Oscillator')
        plt.show()

    return t, x, v


In [30]:
solve_sdof(max_time=10*np.pi, x0 = 0, v0 = 0, plotnow = 1)

(array([  0.00000000e+00,   4.00100949e-03,   8.00201899e-03, ...,
          3.14079245e+01,   3.14119255e+01,   3.14159265e+01]),
 array([  0.00000000e+00,   9.58959444e-06,   3.83122231e-05, ...,
         -2.82897386e-01,  -2.81380343e-01,  -2.79845335e-01]),
 array([ 0.        ,  0.00479155,  0.00956358, ...,  0.37691178,
         0.3814143 ,  0.3858916 ]))

In [33]:
#From nonlinear.py posted by Daniel Clark
import pylab as pl
import numpy as np
import scipy.optimize as sci
import scipy.integrate as sp

# this code is the nonlinear case of \dotdot{x} + \dot{x} + x + x**3 = A*cos(w*t)

def DuffingOscillatorTimeSeriesResults(N = 99,w = 2,A = 1.2):
    t = np.linspace(0, 10*np.pi, N+1)    # time samples of forcing function
    t = t[0:-1]                         # Removing the extra sample
    f = A*np.cos(w*t)                     # My forcing function
    T = t[-1]
    xbar = 0.3/1.2*f

    def FUNCTION(xbar):
        N = len(xbar)
        Xbar = np.fft.fft(xbar)
        omega = np.fft.fftfreq(N, T/(2*np.pi*N) )# + 0.0000001 # list of frequencies
        dotxbar = np.fft.ifft(np.multiply((1j*omega),Xbar))
        dotdotxbar = np.fft.ifft(np.multiply((1j*omega)**2,Xbar))
        R = dotdotxbar + dotxbar + xbar + xbar**3 - f
        R = R**2
        R = np.sum(R)
        return R

    optimizedResults = sci.minimize(FUNCTION, xbar, method='SLSQP')
    xbar = optimizedResults.x

    print(optimizedResults)
    print(xbar)

    pl.plot(t,xbar,t,f,'--')
    pl.legend(['x','Forcing Function'])
    pl.xlabel('Time (s)')
    pl.title('Harmonic Balance Method Response of the Duffing Oscillator')
    pl.show()

In [34]:
DuffingOscillatorTimeSeriesResults(N = 250)

C:\Users\tidba_000\Anaconda3\lib\site-packages\scipy\optimize\slsqp.py:62: ComplexWarning: Casting complex values to real discards the imaginary part
  jac[i] = (func(*((x0+dx,)+args)) - f0)/epsilon
C:\Users\tidba_000\Anaconda3\lib\site-packages\scipy\optimize\slsqp.py:407: ComplexWarning: Casting complex values to real discards the imaginary part
  slsqp(m, meq, x, xl, xu, fx, c, g, a, acc, majiter, mode, w, jw)


 message: 'Iteration limit exceeded'
       x: array([-0.26095906, -0.20655136, -0.13827366, -0.0613689 ,  0.01802601,
        0.09644939,  0.16852184,  0.22882466,  0.27565103,  0.30572243,
        0.31687299,  0.30776637,  0.27889645,  0.23247936,  0.17101492,
        0.09812173,  0.0192064 , -0.06093275, -0.13589595, -0.2024355 ,
       -0.25691726, -0.29572265, -0.31675354, -0.31721062, -0.29808878,
       -0.2600932 , -0.20553998, -0.13835521, -0.0621386 ,  0.0176651 ,
        0.09628427,  0.16835382,  0.22925375,  0.2758395 ,  0.30545991,
        0.31675338,  0.30782991,  0.27943827,  0.23265191,  0.17098379,
        0.09778545,  0.01875993, -0.06069612, -0.13586967, -0.20256467,
       -0.25735021, -0.29542457, -0.31587846, -0.31680996, -0.29839251,
       -0.26065976, -0.2061112 , -0.13863544, -0.06213251,  0.01823722,
        0.0967283 ,  0.16827266,  0.22915596,  0.27614995,  0.30594336,
        0.31649572,  0.30742936,  0.27876205,  0.2326949 ,  0.17059938,
        0.0980439